# Generated by Django 5.2.1 on 2025-05-26 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Worker Name')),
                ('machine_no', models.IntegerField(choices=[(1, 'Machine 1'), (2, 'Machine 2'), (3, 'Machine 3'), (4, 'Machine 4'), (5, 'Machine 5'), (6, 'Machine 6'), (7, 'Machine 7'), (8, 'Machine 8'), (9, 'Machine 9'), (10, 'Machine 10'), (11, 'Machine 11'), (12, 'Machine 12'), (13, 'Machine 13'), (14, 'Machine 14'), (15, 'Machine 15'), (16, 'Machine 16'), (17, 'Machine 17'), (18, 'Machine 18'), (19, 'Machine 19'), (20, 'Machine 20'), (21, 'Machine 21'), (22, 'Machine 22'), (23, 'Machine 23'), (24, 'Machine 24'), (25, 'Machine 25'), (26, 'Machine 26'), (27, 'Machine 27'), (28, 'Machine 28'), (29, 'Machine 29'), (30, 'Machine 30'), (31, 'Machine 31'), (32, 'Machine 32'), (33, 'Machine 33'), (34, 'Machine 34'), (35, 'Machine 35'), (36, 'Machine 36'), (37, 'Machine 37'), (38, 'Machine 38'), (39, 'Machine 39'), (40, 'Machine 40'), (41, 'Machine 41'), (42, 'Machine 42'), (43, 'Machine 43'), (44, 'Machine 44'), (45, 'Machine 45'), (46, 'Machine 46'), (47, 'Machine 47'), (48, 'Machine 48'), (49, 'Machine 49'), (50, 'Machine 50'), (51, 'Machine 51'), (52, 'Machine 52'), (53, 'Machine 53'), (54, 'Machine 54'), (55, 'Machine 55'), (56, 'Machine 56'), (57, 'Machine 57'), (58, 'Machine 58'), (59, 'Machine 59'), (60, 'Machine 60'), (61, 'Machine 61'), (62, 'Machine 62'), (63, 'Machine 63'), (64, 'Machine 64'), (65, 'Machine 65'), (66, 'Machine 66'), (67, 'Machine 67'), (68, 'Machine 68'), (69, 'Machine 69'), (70, 'Machine 70'), (71, 'Machine 71'), (72, 'Machine 72'), (73, 'Machine 73'), (74, 'Machine 74'), (75, 'Machine 75'), (76, 'Machine 76'), (77, 'Machine 77'), (78, 'Machine 78'), (79, 'Machine 79'), (80, 'Machine 80'), (81, 'Machine 81'), (82, 'Machine 82'), (83, 'Machine 83'), (84, 'Machine 84'), (85, 'Machine 85'), (86, 'Machine 86'), (87, 'Machine 87'), (88, 'Machine 88'), (89, 'Machine 89'), (90, 'Machine 90'), (91, 'Machine 91'), (92, 'Machine 92'), (93, 'Machine 93'), (94, 'Machine 94'), (95, 'Machine 95'), (96, 'Machine 96'), (97, 'Machine 97'), (98, 'Machine 98'), (99, 'Machine 99'), (100, 'Machine 100'), (101, 'Machine 101'), (102, 'Machine 102'), (103, 'Machine 103'), (104, 'Machine 104'), (105, 'Machine 105'), (106, 'Machine 106'), (107, 'Machine 107'), (108, 'Machine 108'), (109, 'Machine 109'), (110, 'Machine 110'), (111, 'Machine 111'), (112, 'Machine 112'), (113, 'Machine 113'), (114, 'Machine 114'), (115, 'Machine 115'), (116, 'Machine 116'), (117, 'Machine 117'), (118, 'Machine 118'), (119, 'Machine 119'), (120, 'Machine 120'), (121, 'Machine 121'), (122, 'Machine 122'), (123, 'Machine 123'), (124, 'Machine 124'), (125, 'Machine 125'), (126, 'Machine 126'), (127, 'Machine 127'), (128, 'Machine 128'), (129, 'Machine 129'), (130, 'Machine 130'), (131, 'Machine 131'), (132, 'Machine 132'), (133, 'Machine 133'), (134, 'Machine 134'), (135, 'Machine 135'), (136, 'Machine 136'), (137, 'Machine 137'), (138, 'Machine 138'), (139, 'Machine 139'), (140, 'Machine 140'), (141, 'Machine 141'), (142, 'Machine 142'), (143, 'Machine 143'), (144, 'Machine 144'), (145, 'Machine 145'), (146, 'Machine 146'), (147, 'Machine 147'), (148, 'Machine 148'), (149, 'Machine 149'), (150, 'Machine 150'), (151, 'Machine 151'), (152, 'Machine 152'), (153, 'Machine 153'), (154, 'Machine 154'), (155, 'Machine 155'), (156, 'Machine 156'), (157, 'Machine 157'), (158, 'Machine 158'), (159, 'Machine 159'), (160, 'Machine 160'), (161, 'Machine 161'), (162, 'Machine 162'), (163, 'Machine 163'), (164, 'Machine 164'), (165, 'Machine 165'), (166, 'Machine 166'), (167, 'Machine 167'), (168, 'Machine 168'), (169, 'Machine 169'), (170, 'Machine 170'), (171, 'Machine 171'), (172, 'Machine 172'), (173, 'Machine 173'), (174, 'Machine 174'), (175, 'Machine 175'), (176, 'Machine 176'), (177, 'Machine 177'), (178, 'Machine 178'), (179, 'Machine 179'), (180, 'Machine 180'), (181, 'Machine 181'), (182, 'Machine 182'), (183, 'Machine 183'), (184, 'Machine 184'), (185, 'Machine 185'), (186, 'Machine 186'), (187, 'Machine 187'), (188, 'Machine 188'), (189, 'Machine 189'), (190, 'Machine 190'), (191, 'Machine 191'), (192, 'Machine 192')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(192)], verbose_name='Machine Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('day_1_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 1 Meter')),
                ('day_2_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 2 Meter')),
                ('day_3_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 3 Meter')),
                ('day_4_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 4 Meter')),
                ('day_5_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 5 Meter')),
                ('day_6_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 6 Meter')),
                ('day_7_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 7 Meter')),
                ('day_8_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 8 Meter')),
                ('day_9_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 9 Meter')),
                ('day_10_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 10 Meter')),
                ('day_11_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 11 Meter')),
                ('day_12_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 12 Meter')),
                ('day_13_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 13 Meter')),
                ('day_14_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 14 Meter')),
                ('day_15_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Day 15 Meter')),
                ('rate_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate Per Meter')),
                ('total_meter', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Meter (15 days)')),
                ('total_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Rate (15 days)')),
                ('avg_meter_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Average Meter Per Day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker Production Record',
                'verbose_name_plural': 'Worker Production Records',
                'ordering': ['-date', 'name', 'machine_no'],
                'unique_together': {('name', 'machine_no', 'date')},
            },
        ),
    ]
